apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Chart.Name }}
  labels:
    name: {{ .Chart.Name }}
spec:
  schedule: "1 1 * 1 *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            volumeMounts:
            - mountPath: /home/athena/athena.env
              name: athenaenv
              subPath: athena.env
            command: 
            - "/bin/sh"
            - "-c"
            args: 
              - . /home/athena/athena.env;java -Ddb.server=${DB_HOST} -Ddb.name=Athena -jar -XX:+UseG1GC -Xms256m -Xmx1536m /home/athena/app.jar
          volumes:
            - name: athenaenv
              configMap:
                defaultMode: 420
                name: athenaenv
          restartPolicy: Never