apiVersion: v1
kind: Service
metadata:
  namespace: {{.Release.Namespace}}
  name: {{.Chart.Name}}
  labels:
    svc: {{.Chart.Name}}
spec:
  ports:
    - port: {{.Values.service.port}}
      protocol: TCP
      name: http
  selector:
    app: {{.Chart.Name}}
