---
# tasks file for pilot
- name: create keypair
  amazon.aws.ec2_key:
    name: '{{ ec2_keypair }}'
    region: '{{ aws_region }}'
    tags:
      Name: '{{ ec2_keypair }}'
    force: false
  register: pilot_keypair
- name: save keypair to local
  copy: 
    content: "{{ pilot_keypair.key.private_key }}"
    dest: "{{ key_path }}"
    mode: 0600
  when: pilot_keypair.changed
- name: create pilot security group
  amazon.aws.ec2_group:
    name: pilot security group
    description: Security Group for Pilot Instance
    region: "{{ aws_region }}"
    rules: 
    - proto: tcp
      from_port: 22
      to_port: 22
      cidr_ip: 0.0.0.0/0
    rules_egress:
    - proto: all
      cidr_ip: 0.0.0.0/0
  register: pilot_sg
- name: launch pilot instance
  amazon.aws.ec2_instance:
    instance_type: "{{ ec2_instance_type }}"
    image_id: "{{ ec2_image }}"
    wait: true
    region: "{{ aws_region }}"
    key_name: "{{ ec2_keypair }}"
    security_group: "{{ pilot_sg.group_name }}"
    volumes:
    - device_name: /dev/sda1
      ebs:
        volume_size: 16
        delete_on_termination: true
    count: 1
    state: running
    tags:
      Name: Pilot
  register: pilot_instance
# - name: Add instance to host group
#   add_host:
#     hostname: "{{ item.public_ip_address }}"
#     groupname: launched
#   loop: "{{ pilot_instance.instances }}"
- name: wait for SSH to come up
  wait_for:
    host: "{{ item.public_ip_address }}"
    port: 22
    state: started
  with_items: '{{ pilot_instance.instances }}'
