apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Chart.Name }}
  labels:
    name: {{ .Chart.Name }}
  annotations:
    prometheus.io/path: "/actuator/prometheus"
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        name: {{ .Chart.Name }}
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{.Values.service.port}}
              protocol: TCP
          volumeMounts:
          - mountPath: /home/athena/athena.env
            name: athenaenv
            subPath: athena.env
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            requests:
              cpu: 200m
              memory: "1024Mi"
            limits:
              cpu: 500m
              memory: "2048Mi"
          command: 
          - "/bin/sh"
          - "-c"
          args: 
            - . /home/athena/athena.env;java -jar -Dspring.profiles.active=eks -XX:+UseG1GC -Xms256m -Xmx1024m /home/athena/app.jar  --kafka.bootstrap-servers=${ATHENA_KAFKA_CONSUMERS}  --kafka.consumer.topics=${TENANT_ID}-rideRegistrationChange  --mongo.url=mongodb://${CACHE_HOST}:27017/?uuidRepresentation=STANDARD  --application.athena.tenant.id=${TENANT_ID}  --application.karros.login.url=https://${KARROS_GATEWAY}/api/v1/signin  --application.karros.keycloak.client-id=${KEYCLOAK_ID}  --application.karros.keycloak.client-secret=${KEYCLOAK_SECRET}  --application.karros.keycloak.url=https://${KEYCLOAK_DOMAIN}/auth/realms/Edulog/protocol/openid-connect/token  --application.karros.keycloak.logout-url=https://${KEYCLOAK_DOMAIN}/auth/realms/Edulog/protocol/openid-connect/logout  --application.karros.keycloak.forgot-password-url=https://${KEYCLOAK_DOMAIN}/auth/realms/Edulog/karros-auth/forgot-password
      volumes:
        - name: athenaenv
          configMap:
            defaultMode: 420
            name: athenaenv
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Chart.Name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Chart.Name }}
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metricName: jvm_threads_live_threads
      targetAverageValue: 2500
  - type: Pods
    pods:
      metricName: tomcat_threads_current_threads
      targetAverageValue: 50